from PyQt6 import QtCore, QtGui, QtWidgets
from custom_widgets import CustomQProgressBar


class Interface(object):
    def __init__(self, Form):
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerWidget = QtWidgets.QWidget(parent=Form)
        self.headerWidget.setMinimumSize(QtCore.QSize(480, 35))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_6.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logoLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(20, 21))
        self.logoLabel.setMaximumSize(QtCore.QSize(20, 21))
        self.logoLabel.setPixmap(QtGui.QPixmap(":/icon/img/logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_6.addWidget(self.logoLabel)
        self.headingLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.headingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headingLabel.setObjectName("headingLabel")
        self.horizontalLayout_6.addWidget(self.headingLabel)
        self.headerBtnWidget = QtWidgets.QWidget(parent=self.headerWidget)
        self.headerBtnWidget.setMinimumSize(QtCore.QSize(84, 20))
        self.headerBtnWidget.setMaximumSize(QtCore.QSize(84, 20))
        self.headerBtnWidget.setObjectName("headerBtnWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerBtnWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimizeBtn = QtWidgets.QPushButton(parent=self.headerBtnWidget)
        self.minimizeBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(20, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeBtn.setIcon(icon)
        self.minimizeBtn.setIconSize(QtCore.QSize(14, 14))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_5.addWidget(self.minimizeBtn)
        self.maximizeBtn = QtWidgets.QPushButton(parent=self.headerBtnWidget)
        self.maximizeBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.maximizeBtn.setMaximumSize(QtCore.QSize(20, 20))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/img/maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maximizeBtn.setIcon(icon1)
        self.maximizeBtn.setIconSize(QtCore.QSize(14, 14))
        self.maximizeBtn.setObjectName("maximizeBtn")
        self.horizontalLayout_5.addWidget(self.maximizeBtn)
        self.exitBtn = QtWidgets.QPushButton(parent=self.headerBtnWidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.exitBtn.setMaximumSize(QtCore.QSize(20, 20))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/img/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitBtn.setIcon(icon2)
        self.exitBtn.setIconSize(QtCore.QSize(14, 14))
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_5.addWidget(self.exitBtn)
        self.horizontalLayout_6.addWidget(self.headerBtnWidget)
        self.verticalLayout_2.addWidget(self.headerWidget)
        self.videoWidget = QtWidgets.QWidget(parent=Form)
        self.videoWidget.setObjectName("videoWidget")
        self.videoWidgetLayout = QtWidgets.QVBoxLayout()
        self.videoWidgetLayout.setContentsMargins(0,0,0,0)
        self.videoWidget.setLayout(self.videoWidgetLayout)
        self.verticalLayout_2.addWidget(self.videoWidget)
        self.playerWidget = QtWidgets.QWidget(parent=Form)
        self.playerWidget.setMinimumSize(QtCore.QSize(480, 80))
        self.playerWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.playerWidget.setObjectName("playerWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.playerWidget)
        self.verticalLayout.setContentsMargins(7, 11, 7, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeLineWidget = QtWidgets.QWidget(parent=self.playerWidget)
        self.timeLineWidget.setMinimumSize(QtCore.QSize(0, 18))
        self.timeLineWidget.setMaximumSize(QtCore.QSize(16777215, 18))
        self.timeLineWidget.setObjectName("timeLineWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.timeLineWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.currentDurationLabel = QtWidgets.QLabel(parent=self.timeLineWidget)
        self.currentDurationLabel.setMinimumSize(QtCore.QSize(58, 18))
        self.currentDurationLabel.setMaximumSize(QtCore.QSize(58, 18))
        self.currentDurationLabel.setObjectName("currentDurationLabel")
        self.horizontalLayout_4.addWidget(self.currentDurationLabel)
        self.videoTimeLine = CustomQProgressBar(parent=self.timeLineWidget)
        self.videoTimeLine.setMinimumSize(QtCore.QSize(0, 10))
        self.videoTimeLine.setMaximumSize(QtCore.QSize(16777215, 10))
        self.videoTimeLine.setProperty("value", 0)
        self.videoTimeLine.setTextVisible(False)
        self.videoTimeLine.setObjectName("videoTimeLine")
        self.horizontalLayout_4.addWidget(self.videoTimeLine)
        self.videoDurationLabel = QtWidgets.QLabel(parent=self.timeLineWidget)
        self.videoDurationLabel.setMinimumSize(QtCore.QSize(58, 18))
        self.videoDurationLabel.setMaximumSize(QtCore.QSize(58, 18))
        self.videoDurationLabel.setObjectName("videoDurationLabel")
        self.horizontalLayout_4.addWidget(self.videoDurationLabel)
        self.verticalLayout.addWidget(self.timeLineWidget)
        self.controlWidget = QtWidgets.QWidget(parent=self.playerWidget)
        self.controlWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.controlWidget.setObjectName("controlWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.controlWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftControlWidget = QtWidgets.QWidget(parent=self.controlWidget)
        self.leftControlWidget.setMaximumSize(QtCore.QSize(106, 30))
        self.leftControlWidget.setObjectName("leftControlWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.leftControlWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backwordBtn = QtWidgets.QPushButton(parent=self.leftControlWidget)
        self.backwordBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.backwordBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/img/backword.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backwordBtn.setIcon(icon3)
        self.backwordBtn.setIconSize(QtCore.QSize(24, 24))
        self.backwordBtn.setObjectName("backwordBtn")
        self.horizontalLayout_2.addWidget(self.backwordBtn)
        self.playBtn = QtWidgets.QPushButton(parent=self.leftControlWidget)
        self.playBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.playBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/img/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playBtn.setIcon(icon4)
        self.playBtn.setIconSize(QtCore.QSize(24, 24))
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_2.addWidget(self.playBtn)
        self.forwordBtn = QtWidgets.QPushButton(parent=self.leftControlWidget)
        self.forwordBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.forwordBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/img/forword.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.forwordBtn.setIcon(icon5)
        self.forwordBtn.setIconSize(QtCore.QSize(24, 24))
        self.forwordBtn.setObjectName("forwordBtn")
        self.horizontalLayout_2.addWidget(self.forwordBtn)
        self.horizontalLayout.addWidget(self.leftControlWidget)
        self.rightControlWidget = QtWidgets.QWidget(parent=self.controlWidget)
        self.rightControlWidget.setMinimumSize(QtCore.QSize(250, 30))
        self.rightControlWidget.setMaximumSize(QtCore.QSize(250, 30))
        self.rightControlWidget.setObjectName("rightControlWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.rightControlWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.repeatBtn = QtWidgets.QPushButton(parent=self.rightControlWidget)
        self.repeatBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.repeatBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/img/repeat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.repeatBtn.setIcon(icon6)
        self.repeatBtn.setIconSize(QtCore.QSize(24, 24))
        self.repeatBtn.setObjectName("repeatBtn")
        self.horizontalLayout_3.addWidget(self.repeatBtn)
        self.fullScreenBtn = QtWidgets.QPushButton(parent=self.rightControlWidget)
        self.fullScreenBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.fullScreenBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/img/full_screen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fullScreenBtn.setIcon(icon7)
        self.fullScreenBtn.setIconSize(QtCore.QSize(24, 24))
        self.fullScreenBtn.setObjectName("fullScreenBtn")
        self.horizontalLayout_3.addWidget(self.fullScreenBtn)
        self.muteBtn = QtWidgets.QPushButton(parent=self.rightControlWidget)
        self.muteBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.muteBtn.setMaximumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/img/speaker_100%.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.muteBtn.setIcon(icon8)
        self.muteBtn.setIconSize(QtCore.QSize(24, 24))
        self.muteBtn.setObjectName("muteBtn")
        self.horizontalLayout_3.addWidget(self.muteBtn)
        self.volumeSlider = QtWidgets.QSlider(parent=self.rightControlWidget)
        self.volumeSlider.setMinimumSize(QtCore.QSize(136, 19))
        self.volumeSlider.setMaximumSize(QtCore.QSize(136, 19))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setSingleStep(5)
        self.volumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_3.addWidget(self.volumeSlider)
        self.horizontalLayout.addWidget(self.rightControlWidget)
        self.verticalLayout.addWidget(self.controlWidget)
        self.verticalLayout_2.addWidget(self.playerWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.headingLabel.setText(_translate("Form", "YT Player"))
        self.currentDurationLabel.setText(_translate("Form", "00:00:00"))
        self.videoDurationLabel.setText(_translate("Form", "00:00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Interface(Form)
    Form.show()
    sys.exit(app.exec())
